/**
 *@file readFile.c
 *@Author Clayton Dembski
 *@date Sep 15, 2017
 * when the program getArrtoAppend is run with a given file in the format x, o,
 * an array is created of the file, this is passed back.
 */

#include "readFile.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>


/**extracts the maximum row size of a given file in xo life format
*@param fileName[] The name of the fie to extract the row size from
*@return the max row length of the given file.
*/
int getArrRow(char fileName[]){
  FILE *input;
  int r=0; //max row of the file
  char scroll=0;//current value in current position of file

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }

//precondition: the given file has been opened and is at the first index.
  while(scroll!=EOF){
    scroll = fgetc(input);
    if(scroll == '\n'){
      r++;
    }
    //loopInvariant: the max row size has been found
                      //scroll is at the end of the file
  }
  fclose(input);
  return r;

}

///////////////////////////////////////////////////////////////

/**extracts the maximum column size of a given file in xo life format
*@param fileName[] The name of the file to extract the row size from
*@return the max column length of the given file.
*/

int getArrCol(char fileName[]){
  FILE *input;
  int c=0;//relitive column  value for row
  int cMax = 0; //max column row for file
  char scroll=0;//current value in current position of file

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }
//precondition: the given file has been opened and is at the first index.
  while(scroll!=EOF){
    fflush(stdout);
    scroll = fgetc(input);
    c++;
    if(scroll=='\n'){
      if(c>cMax)
        cMax = c;
      c=0;//loop invariant: the max column size has been found,
                            //scroll is at the end of the file
    }

  }

  fclose(input);
  return cMax;
}

///////////////////////////////////////////////////////////////

/**this creates a 2 dimentional array of the data stored,
*assuming the file is in the proper xo life format.
*@param fileName[] The name of the file to extract the array from
*@return a 2 dimentional array of the given file
*/
int** getArrToAppend(char fileName[]){
  int i;//indexor
  int r;//row indexer of life array
  int c;//column indexer of life array

  int rSize = getArrRow(fileName);//max size of r
  fflush(stdout);
  int cSize = getArrCol(fileName)-1;//maxsize of c
  fflush(stdout);
  int** genAppend = (int **)malloc(rSize*sizeof(int *));//life array from file
  //precondition: genAppend is a 2d array allocated to store arrays of pointers
                  //in each row.
	if (genAppend) for (i=0; i<rSize; i++){
		genAppend[i] = (int*)malloc(cSize * sizeof(int));
		if (!genAppend[i]) exit(-1);
  }//loopInvariant: genAppend will be a 2d array of pointers.

//precondition: all three boards are empty
  for(r=0;r<rSize;r++){
    for(c=0;c<cSize;c++){
      genAppend[r][c]=0;
    }
  }
//loop invariant all three boards are filled with 0s

  updateArray(fileName, genAppend);

  return genAppend;
}

///////////////////////////////////////////////////////////////

/**with a filename and a blank array of bounds generated by the max extents
*of the file, (row and column) fill in any spaces that contain x's in the array
*this is to account for arrays that are uneven in size, line by line.
*@param fileName[] The name of the file to extract the coordinates of life from
*@param genAppend The empty matrix to append "live" cells to.
*/
void updateArray(char fileName[], int ** genAppend){
  FILE *input;
  int r=0;
  int c=-1;
  char scroll = 0;

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }

//precondition: the given file has been opened and is at the first index.
  while(scroll!=EOF){
    scroll = fgetc(input);
    if(scroll == '\n'){
        r++;
        c=-1;
    }
    else{
      c++;
    }
    if (scroll == 'x'){
      genAppend[r][c] = 1;
    }
    if (scroll == 'o'){
      genAppend[r][c] = 0;
    }

  }//loopInvariant: the life array has been filled with life from the given file

  fclose(input);
}
