#include "readFile.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>


/**extracts the maximum row size of a given file in xo life format
*@param fileName[] The name of the fie to extract the row size from
*@return the max row length of the given file.
*/
int getArrRow(char fileName[]){
  FILE *input;
  int r=0;
  char scroll=0;

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }

  while(scroll!=EOF){
    scroll = fgetc(input);
    if(scroll == '\n'){
      r++;
    }
  }
  fclose(input);
  return r;

}

///////////////////////////////////////////////////////////////

/**extracts the maximum column size of a given file in xo life format
*@param fileName[] The name of the file to extract the row size from
*@return the max column length of the given file.
*/
int getArrCol(char fileName[]){
  FILE *input;
  int c=0;
  int cMax = 0;
  char scroll=0;

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }

  while(scroll!=EOF){
    fflush(stdout);
    scroll = fgetc(input);
    c++;
    if(scroll=='\n'){
      if(c>cMax)
        cMax = c;
      c=0;
    }

  }

  fclose(input);
  return cMax;
}

///////////////////////////////////////////////////////////////

/**this creates a 2 dimentional array of the data stored,
*assuming the file is in the proper xo life format.
*@param fileName[] The name of the file to extract the array from
*@return a 2 dimentional array of the given file
*/
int** getArrToAppend(char fileName[]){
  int i;
  int r;
  int c;

  int rSize = getArrRow(fileName);
  fflush(stdout);
  int cSize = getArrCol(fileName)-1;
  fflush(stdout);
  int** genAppend = (int **)malloc(rSize*sizeof(int *));
	if (genAppend) for (i=0; i<rSize; i++){
		genAppend[i] = (int*)malloc(cSize * sizeof(int));
		if (!genAppend[i]) exit(-1);
  }

  for(r=0;r<rSize;r++){
    for(c=0;c<cSize;c++){
      genAppend[r][c]=0;
    }
  }

  updateArray(fileName, genAppend);

  return genAppend;
}

///////////////////////////////////////////////////////////////

/**with a filename and a blank array of bounds generated by the max extents
*of the file, (row and column) fill in any spaces that contain x's in the array
*this is to account for arrays that are uneven in size, line by line.
*@param fileName[] The name of the file to extract the coordinates of life from
*@param genAppend The empty matrix to append "live" cells to.
*/
void updateArray(char fileName[], int ** genAppend){
  FILE *input;
  int r=0;
  int c=-1;
  char scroll = 0;

  input = fopen(fileName, "r");
  if (!input){
    printf("Unable to open file\n");
    fflush(stdout);
    exit(-0);
  }

  while(scroll!=EOF){
    scroll = fgetc(input);
    if(scroll == '\n'){
        r++;
        c=-1;
    }
    else{
      c++;
    }
    if (scroll == 'x'){
      genAppend[r][c] = 1;
    }
    if (scroll == 'o'){
      genAppend[r][c] = 0;
    }

  }

  fclose(input);
}
